export const FETCH_TYPES = {
  ASYNC_POSTS_REQUEST: 'ASYNC_POSTS_REQUEST',
  ASYNC_POSTS_SUCCESS: 'ASYNC_POSTS_SUCCESS',
  ASYNC_POSTS_FAILED: 'ASYNC_POSTS_FAILED',
}
export const TYPES = {
  THEME: 'THEME'
}


